### ISSUE TITLE
I want to adapt this for 2 to 5 hp motor

### ISSUE THREAD

**Issue by bkrajendra** [roboterclubaachen/micro-motor#2]
I want to adapt this for 2 to 5 hp motor.
I am planning to develop a solar powered BLDC motor pump without using any batteries.
SOPV   + MPPT tracking + BLDV driver-> BLDC Motor.

What changes need to be done to handle these voltage levels?

**Comment by rleh** [comment]
Hi @bkrajendra!

> I want to adapt this for 2 to 5 hp motor.
> I am planning to develop a solar powered BLDC motor pump without using any batteries.
> SOPV + MPPT tracking + BLDV driver-> BLDC Motor.

Could be possible.

> What changes need to be done to handle these voltage levels?

With which voltage will your system run? Solar systems are available from 5V to >1kV...

**Comment by bkrajendra** [comment]
Thank you for the quick reply.
A typical solar panel I was targeting was about 250Watt, 37.7 V, 9Amp max current
The target motors are about 1 to 3HP.

I might be wrong with the few details, but the ultimate aim is to drive up to 3hp (max 5hp) BLDC motors directly through Solar PV.

**Comment by rleh** [comment]
> A typical solar panel I was targeting was about 250Watt, 37.7 V, 9Amp max current
> The target motors are about 1 to 3HP.

But 250W != 3HP, so you somehow have to connect multiple panels together. Willy they be in series or parallel connection?

As far as I remember, most components which are connected to the "+24V" voltage rail in the schematics are 60V rated, or at least 40V rated.
Assuming a system voltage of 37.7V, the 60V components should be fine, any 40V or lower rated chips have to be replaced.
The best thing to do is to go through the schematic and look at all the components.

You also have to replace al least the MOSFETs with larger ones.

Also note the separate "Logic" voltage supply (+6V to +12V used in past Roboterclub applications), which is down-converted to +3.3V by the TPS82150 integrated DC/DC converter chip. If you want to use a single supply you would also have to replace that chip.

---

Maybe it could be easier to use/adapt another open source motor controller for your application, that was initial designed for higher power and voltages, like [VESC](https://vesc-project.com/) (https://github.com/vedderb/bldc-hardware) or https://github.com/SDI-SoftwareDefinedInverter/TAPAS?!
